=== azuberogon/lgmaRm/xsd/ejercicios/ejercicio 3/ejercicio 3.2/library.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="lang" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="author">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="date" type="xs:date"/>
                    <xs:element name="nationality" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="publication">
                <xs:complexType>
                  <xs:attribute name="date" type="xs:date"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isbn" type="xs:string"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="description">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="year" type="xs:gYear"/>
              <xs:element name="city" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="lang" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string"/>
      <xs:attribute name="nif" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== azuberogon/lgmaRm/xsd/ejercicios/ejercicio 3/ejercicio 3.2/library.xml
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="library.xsd"
         nombre="Babel" nif="21354645D"> 
    <book isbn="ASDFGH123"> 
        <title lang="SP">El se√±or de los anillos</title>
        <title lang="EN">The lord of the rings</title>
        <author>
            <date>2000-10-10</date>
            <nationality>Sudafricana</nationality>
        </author>
        <publication date="1954-07-29"/> 
    </book>
    <description lang="SP">
        Library <name>Babel</name> founded in <year>2002</year>. It was
        a proposal of many literature lovers in <city>Pamplona</city>
    </description>
</library>
